# Generated by Django 5.1.7 on 2025-10-13 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_venta_cantidad_remove_venta_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion',
            new_name='correo_electronico',
        ),
    ]
