# Generated by Django 5.1.7 on 2025-11-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_factura_detallefactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
